name: Reddit MCP Bot Group 1

on:
  # schedule:
   # - cron: "23 13 * * *"   # 6:23 AM PST
   # - cron: "42 16 * * *"   # 9:42 AM PST
   # - cron: "17 19 * * *"   # 12:17 PM PST
   # - cron: "51 21 * * *"   # 2:51 PM PST
   # - cron: "37 4 * * *"    # 9:37 PM PST
  workflow_dispatch:
    inputs:
      bot_id:
        description: 'Specific bot ID to run (leave empty to run all)'
        required: false

jobs:
  run-bot:
    runs-on: ubuntu-22.04  # 👈 fix: use a stable Ubuntu version
    strategy:
      matrix:
        bot_id: ["logistics1","logistics2","slime","slime","slime2","ai1"]
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Print Python version
        run: python --version
        
      - name: Unset proxy environment variables
        run: |
          # Unset proxy variables that might interfere with Groq
          unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy no_proxy NO_PROXY || true
          # Verify they're unset
          echo "Checking for proxy variables:"
          env | grep -i proxy || echo "No proxy variables found"


      - name: Install dependencies
        run: pip install -r servers/reddit_server/requirements.txt
        
      - name: Install specific Groq version
        run: |
          pip uninstall -y groq
          pip install groq==0.4.1
          
      - name: Print debug information
        run: |
          echo "Installed packages:"
          pip list
          echo "\nGroq version:"
          python -c "import groq; print(groq.__version__)"
          echo "\nEnvironment variables:"
          env | grep -i proxy || echo "No proxy variables found"

      - name: Run Groq test script
        run: |
          python servers/reddit_server/github_actions_test.py
          
      - name: Run bot
        if: ${{ github.event.inputs.bot_id == '' || matrix.bot_id == github.event.inputs.bot_id }}
        run: |
          # python servers/reddit_server/bot_runner.py --dry-run --max-subreddits 20 --max-replies 2 --max-upvotes 4 --bot-id ${{ matrix.bot_id }}
          python servers/reddit_server/bot_runner.py --max-subreddits 20 --max-replies 2 --max-upvotes 4 --bot-id ${{ matrix.bot_id }}


